### PR TITLE
Initial pass of deleting call recordings use case

### PR DESCRIPTION
**Pull request by tbass134**

### CODE REVIEW

**Comment by niati** [comment]
@tbass134 Some of the hyperlinks are broken in the review app. For instance, when I click the 'Create an application' link in the Prerequisites section, the page doesn't exist. Try editing the following links in Prerequisites section to: 

[guide](/concepts/guides/create-a-developer-account)

[Create an application](/concepts/guides/create-an-application)

[Subscribe to the API's](/concepts/guides/subscribe-to-apis)

**Comment by tbass134** [comment]
Thanks @niati Those links are fixed

**Comment by niati** [comment]
Found another link in Authentication section (sorry!):

Making an API Request guide: /concepts/guides/make-an-api-request

**Comment by tbass134** [comment]
Thanks @niati i fixed that one as well

**Pull request merged**
